name: rlut

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++11
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  rlut-test:
    type: tool
    platform: macOS
    sources:
        - path: aux/test.c
    dependencies:
        - target: rlut
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps]
  rlut-gui-test:
    type: tool
    platform: macOS
    sources:
        - path: aux/test.c
    dependencies:
        - target: rlut-gui
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps]
  rlut:
    type: library.dynamic
    platform: macOS
    sources:
        - path: src/
        - path: deps/imtui
          includes:
            - "*.cpp"
          excludes:
            - "*emscripten*"
        - path: deps/imgui
          includes:
            - "*.cpp"
        - path: deps/
          type: folder
        - path: aux/
          type: folder
        - path: README.md
          type: folder
        - path: Makefile
          type: folder
        - path: project.yml
          type: folder
    dependencies:
        - sdk: libncurses.tbd
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps]
        OTHER_CFLAGS: ["-x objective-c++", -fobjc-arc]
  rlut-gui:
    type: library.dynamic
    platform: macOS
    sources:
        - path: src/
        - path: deps/imgui
          includes:
            - "*.cpp"
            - "backends/imgui_impl_sdl.cpp"
            - "backends/imgui_impl_opengl3.cpp"
    dependencies:
        - sdk: /opt/homebrew/lib/libSDL2.dylib
        - sdk: AppKit.framework
    settings:
        HEADER_SEARCH_PATHS: [/opt/homebrew/include,
                              $(PROJECT_DIR)/deps]
        LIBRARY_SEARCH_PATHS: [/opt/homebrew/lib]
        OTHER_CFLAGS: [-DRLUT_SDL2, "-x objective-c++", -fobjc-arc]
